# Generated by Django 4.0.4 on 2022-06-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_us',
        ),
    ]
