# Generated by Django 4.0.4 on 2022-06-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0002_delete_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
