# Generated by Django 4.0.4 on 2022-06-07 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0003_alter_profesor_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='last_name',
            new_name='Apellido',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='name',
            new_name='Deporte',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='sport',
            new_name='Nombre',
        ),
    ]
